
```{r}
# Question 1
library(tidyverse)
# a.
flower_df <- tibble(
  species = c("setosa", "versicolor", "virginica"),
  petal.length = c(1.4, 4.7, 6),
  petal.width = c(0.2, 1.4, 2.5)
)
flower_df
```

```{r}
# b.
library(tibble)

flower_tribble_df <- tribble(
  ~species,     ~petal.length, ~petal.width,
  "setosa",        1.4,           0.2,
  "versicolor",    4.7,           1.4,
  "virginica",     6.0,           2.5
)

flower_tribble_df
```
```{r}
#c.
flower_df <- flower_df |>
  mutate(petal.area = petal.length * petal.width)
flower_df
```
```{r}
# d.
flower_df |>
  mutate(
    species = str_to_title(species)
  )
flower_df
```
```{r}
# e.
flower_df <- flower_df |>
  mutate(
    long.petal = if_else(petal.length > 4, "long", "short")
  )
flower_df
```
```{r}
# f.
flower_df |>
  arrange(long.petal, desc(petal.width))
flower_df
# Arranging the data frame like this seems to order the character variables in alphabetical order.
```
```{r}
# g.
letters_tibble <- tibble(letter = c("a", "A", "b", "B", "1", "2"))

# Sort by the column 'letter'
letters_sorted <- letters_tibble |>
  arrange(letter)

letters_sorted
# Based on this outcome, R seems to sort in the order of numbers, upper case letter, then lower case letters.
```
```{r}
# Question 2
# a.
mt_cars_df <- as_tibble(mtcars, rownames = "model.name")

mt_cars_df
```
```{r}
# b.
mt_cars_df <- mt_cars_df |>
  select(model.name, mpg, cyl, hp, wt, qsec)

mt_cars_df
```
```{r}
# c.
mt_cars_df <- mt_cars_df |>
  mutate(hp.per.wt = hp / wt)

mt_cars_df
```
```{r}
# d.
mt_cars_df <- mt_cars_df |>
  mutate(fast = hp > 100 & qsec < 18)

mt_cars_df
```
```{r}
# e.
mt_cars_df <- mt_cars_df |>
  mutate(heavy = wt > median(wt))
mt_cars_df
```
```{r}
# f.
names(mt_cars_df) <- names(mt_cars_df) |>
  str_replace_all("_", ".") |>            
  str_replace_all("qsec", "quarter.mile.time") |>
  str_replace_all("wt", "weight") |>
  str_replace_all("mpg", "miles.per.gallon") |>
  str_replace_all("cyl", "cylinders") |>
  str_replace_all("disp", "displacement") |>
  str_replace_all("hp", "horsepower") |>
  str_replace_all("drat", "rear.axle.ratio") |>
  str_replace_all("vs", "engine") |>
  str_replace_all("am", "transmission") |>
  str_replace_all("gear", "gears") |>
  str_replace_all("carb", "carburetors")
mt_cars_df
```
```{r}
# g.
# This doesn't work because the str_split() function only works with a vector, not a list. Also if you index with double brackets, it only selects the first element of the list.
```

```{r}
# h.
mt_cars_table <- mt_cars_df |>
  slice(1:5) |>  
  rename_with(~ str_replace_all(., "\\.", " ")) |>
  rename_with(~ str_to_title(.)) 
mt_cars_table
```
```{r}
# i.
tidy_names <- function(names_vector) {
  names_vector |>
    str_replace_all(" ", ".") |>   
    str_to_lower()                  
}

mt_cars_table <- mt_cars_table |>
  rename_with(tidy_names)

mt_cars_table
# geom_col() <- bar plot
#fct_reorder <- order factor by another column in the data frame
#as_factor <- creates in whatever order factors are in the data frame

library(tidyverse)
library(palmerpenguins)
library(ggthemes)

as_tibble(penguins)
penguins |>
  drop_na(sex) |>
  group_by(species, year) |>
  summarize(n = n(), .groups = "drop") |>
  arrange(year) |>
  mutate(year = as_factor(year)) |>
  ggplot(aes(y = n, x = species, fill = year)) +
  geom_col(position = "dodge") +
  scale_fill_colorblind() +
  labs(
    title = "Observations by species and year",
    x = "", 
    y = "Number of Observations",
    fill = "Year"
   )
```

