
```{r}
# Question 1
```

```{r}
# a.
library(tidyverse)
load("/Users/noahdidonna/Downloads/FAF.Rda")
```

```{r}
# b.
summary(FAF_df)
library(skimr)
skim(FAF_df)
# In this set of data, a row appears to be single freight that corresponds with a year, commodity, and mode of transportation.

# A anit of observation could be the origin, destination, mode of transportation, etc.

colSums(is.na(FAF_df))
```

```{r}
# c.
FAF_df <- FAF_df |>
  rename_with(~ .x |> 
    str_to_lower() |>
    str_replace_all("\\.+", "_") |>
    str_replace_all("\\s+", "_"))

FAF_df  
```
```{r}
# d.
FAF_df <- FAF_df |>
  separate(dms_orig, into = c("orig_code", "orig_label"), sep = " - ", remove = FALSE) |>
  separate(dms_dest, into = c("dest_code", "dest_label"), sep = " - ", remove = FALSE) |>
  separate(sctg2, into = c("sctg_code", "sctg_label"), sep = " - ", remove = FALSE) |>
  separate(dms_mode, into = c("mode_code", "mode_label"), sep = " - ", remove = FALSE)

FAF_df <- FAF_df |>
  mutate(
    orig_code = factor(orig_code, levels = unique(orig_code)),
    dest_code = factor(dest_code, levels = unique(dest_code)),
    sctg_code = factor(sctg_code, levels = unique(sctg_code)),
    mode_code = factor(mode_code, levels = unique(mode_code)),
    
    orig_label = as.character(orig_label),
    dest_label = as.character(dest_label),
    sctg_label = as.character(sctg_label),
    mode_label = as.character(mode_label),
  )
    
num_cols <- c(
  "thousand_tons_in_2017", "million_dollars_in_2017", "current_million_dollars_in_2017",
  "million_ton-miles_in_2017", "thousand_tons_in_2018", "million_dollars_in_2018",
  "current_million_dollars_in_2018", "million_ton-miles_in_2018",
  "thousand_tons_in_2019", "million_dollars_in_2019", "current_million_dollars_in_2019",
  "million_ton-miles_in_2019", "thousand_tons_in_2020", "million_dollars_in_2020",
  "current_million_dollars_in_2020", "million_ton-miles_in_2020",
  "thousand_tons_in_2021", "million_dollars_in_2021", "current_million_dollars_in_2021",
  "million_ton-miles_in_2021", "thousand_tons_in_2022", "million_dollars_in_2022",
  "current_million_dollars_in_2022", "million_ton-miles_in_2022"
)

FAF_df <- FAF_df |>
  mutate(across(all_of(num_cols), ~ as.numeric(str_replace_all(.x, ",", ""))))

skim(FAF_df)
```
```{r}
# Question 2
# a.

library(readxl)
population_data <- read_excel("Copy of population.xlsx") |>
  rename_with(\(x) str_replace_all(x, " ", "_"))
```
```{r}
# b.
skim(population_data)
summary(population_data)

# The rows seem to represent each individual state while the columns represent the year and population

# Years appear in seperate columns, so the data is in wide format.

# The years in the population data only include 2020-2022, while the years in the freight data set range from 2017-2022.
```
```{r}
# b.
unique(FAF_df$dms_orig)
unique(population_data$`table_with_row_headers_in_column_A_and_column_headers_in_rows_3_through_4._(leading_dots_indicate_sub-parts)`)

# The regions are similar, but not exactly the same.

colSums(is.na(population_data))

# There are some missing values. 2 in column 1, 7 in column 3, and 8 in columns 2, 4 and 5.
```
```{r}
# c.
# population_data <- population_data |> select(-"...2"), used this to get rid of column April 1, 2020 Estimates Base.
  
#population_data <- population_data |> filter(!`table_with_row_headers_in_column_A_and_column_headers_in_rows_3_through_4._(leading_dots_indicate_sub-parts)` %in% c("United States", "Midwest", "Northeast", "South", "West", ".Puerto Rico"))

population_data <- population_data |>
  rename_with(~ str_replace_all(., " ", "_")) |>
  rename_with(str_to_lower)

population_data <- population_data |>
  mutate(...3 = as.numeric(...3)) |>
  mutate(...4 = as.numeric(...4)) |>
  mutate(...5 = as.numeric(...5))
```

```{r}
# Part II, 1.
ct_2017_summary <- FAF_df |>
  filter(dms_dest == "09-Connecticut") |>
  group_by(dms_mode) |>
  summarize(total_value_2017 = sum(million_dollars_in_2017, na.rm = TRUE)) |>
  arrange(match(dms_mode, c("Truck", "Rail", "Water", 
                            "Air (include truck-air)", 
                            "Multiple modes & mail", "Pipeline")))

ct_2017_summary
```
```{r}
# Part II, Question 2
population_summary_2022 <- population_data |>
  mutate(
    mean_pop = mean(...5, na.rm = TRUE),
    sd_pop = sd(...5, na.rm = TRUE),
    sd_from_mean = (...5 - mean_pop) / sd_pop,
    size_category = case_when(
      sd_from_mean < -1 ~ "below average",
      sd_from_mean > 1  ~ "above average",
      TRUE              ~ "average"
    )
  ) |>
  arrange(desc(...5)) |>
  select(`table_with_row_headers_in_column_a_and_column_headers_in_rows_3_through_4._(leading_dots_indicate_sub-parts)`, ...5, sd_from_mean, size_category)

head(population_summary_2022)

```
```{r}
# Part II: Plots
# Question 1
library(ggthemes)  
FAF_df |>
  ggplot(aes(x = thousand_tons_in_2017, y = million_dollars_in_2017, color = dms_mode)) +
  geom_point(aes(color = dms_mode)) +
  geom_smooth(method = "lm", formula = y ~ x, na.rm = TRUE) +
  labs(
    title = "Other Ag Prods. Freight Value vs. Quantity in 2017",
    subtitle = "(Values and Quantities less than 1000)",
    x = "Thousand tons",
    y = "Million dollars",
    color = "Mode"
  ) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 250)) +
  scale_y_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 250)) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_text(size = 12),
    legend.title = element_text(size = 11)
  ) +
  scale_color_colorblind()
# Couldn't figure out how to get rid of the "pipeline" and "Other and unknown" modes.

```
```{r}
# Question 2
FAF_df |> 
  ggplot(aes(x = dms_orig, y = million_dollars_in_2017, fill = dms_mode)) +
  geom_col() +  
  labs(
    title = "Cereal Grains Truck Freight to Connecticut in 2017",
    x = "Origin",
    y = "million_dollars_in_2017",
    fill = "Mode"
  ) +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_text(size = 12),
    legend.title = element_text(size = 11)
  )

```
```{r}
# Question 3
top10_pop_2022 <- population_data |>
  arrange(desc(...5)) |>
  slice_head(n = 10)


ggplot(top10_pop_2022, aes(x = ...5, y = `table_with_row_headers_in_column_a_and_column_headers_in_rows_3_through_4._(leading_dots_indicate_sub-parts)`)) +
  geom_col(fill = "grey") +
  coord_flip() +  
  labs(
    title = "Top 10 State Populations in 2022",
    x = "population",
    y = "state"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_text(size = 12)
  )

```
```{r}
# Question 4.
#population_data <- population_data |>
  #rename(state = `table_with_row_headers_in_column_a_and_column_headers_in_rows_3_through_4._(leading_dots_indicate_sub-parts)`)

#states_A_long <- population_data |>
  #filter(grepl("^A", state)) |>
  #pivot_longer(
    #cols = starts_with("..."),   
    #names_to = "year",           
    #values_to = "population"      
  #) |>
  #mutate(
    #year = as.integer(gsub("\\.\\.\\.", "", year))
  #)

#ggplot(states_A_long, aes(x = year, y = population, color = state)) +
  #geom_line(size = 1.2) +
  #labs(
    #title = "State Populations Over Time",
    #x = "year",
    #y = "population",
    #color = "state"
  #) +
  #theme_minimal() +
  #)

```

